modules.export = {
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    es6: true,
  },
  plugins: ['simple-import-sort', 'import'],
  extends: ['eslint:recommended'],
  globals: {
    document: true,
    window: true,
    console: true,
  },
  ignorePatterns: [
    '!.*/**',
    '!.*',
    '!/*.js',
    '/build',
    '/node_modules',
    '/coverage',
    '/dist',
    '/public',
    '/scripts',
    '/public',
    '/legacy',
  ],
  rules: {
    'consistent-return': 'warn',
    'default-param-last': 'off',
    'implicit-arrow-linebreak': 'off',
    'import/named': 'off',
    'import/no-cycle': 'off',
    'import/prefer-default-export': 'off',
    'jsx-a11y/no-autofocus': 'off',
    'no-console': 'warn',
    'no-multiple-empty-lines': [2, { max: 1, maxEOF: 0 }],
    'no-redeclare': 2,
    'no-shadow': 'off',
    'no-undef': 'warn',
    'no-unused-vars': [
      'warn',
      {
        vars: 'all',
        args: 'none',
        ignoreRestSiblings: true,
      },
    ],
    'prettier/prettier': 2,
    'react/destructuring-assignment': 'off',
    'react/function-component-definition': 'off',
    'react/jsx-props-no-spreading': 'off',
    'simple-import-sort/exports': 'error',
    'simple-import-sort/imports': [
      'error',
      {
        groups: [
          [
            '^(fs|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)',
          ],
          [
            '^react',
            '^@?\\w',
            '^@fortawesome',
            'prop-types',
            'classnames',
            'react-native-classnames',
          ],
          ['^@types', '^@constants', '^@services', '^@hooks', '^@utils'],
          ['^@actions', '^@selectors', '^@content'],
          ['^@shared'],
          [
            '^@pages',
            '^@stacks',
            '^@screens',
            '^@components',
            '^@images',
            '^@assets',
            '^@styles',
          ],
          ['^\\u0000'],
          ['^\\.\\.(?!/?$)', '^\\.\\./?$'],
          ['^\\./(?=.*/)(?!/?$)', '^\\.(?!/?$)', '^\\./?$', '^.+\\.s?css$'],
        ],
      },
    ],
  },
};
